spring:
  application:
    name: postgresql-jsonb-index
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
 # jpa:
 #   generate-ddl: false  # только ручное создание объектов БД
 #   show-sql: false # дубликат, см. logging ниже
 #   properties:
 #     hibernate:
 #       format_sql: true
#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog-master.yaml

# embedded Tomcat
#server:
#  port: 8080

#logging:
#  level:
#    org.apache.http: INFO
#    org.springframework.transaction.interceptor: WARN # поставить в TRACE для получения информации по транзакциям
#    org.hibernate:
#      SQL: debug
#      type: trace
#    root: info
#    org.springframework.graphql: debug

#myservice:
#  topics:
#    main-topic: my-topic